name: hibp
base: core24
version: '0.1' 
summary: Have I been pawned database downloader, server and utilities
description: |
  High performance downloader, query tool, server and utilities for the
  Have I been Pawned database of compromiseed passwords. This very useful
  database is somewhat challenging to use locally because of its sheer size.
  These utiliities make it easy and fast to deal with the large data volume
  while being very effiicent on disk and memory resouces.

grade: stable
confinement: strict
lint:
  ignore:
    - library

apps:
  download:
    command: usr/bin/hibp-download
    plugs: [files, network]
  search:
    command: usr/bin/hibp-search
    plugs: [files]
  server:
    command: usr/bin/hibp-server
    plugs: [files, bind]
  join:
    command: usr/bin/hibp-join
    plugs: [files]
  sort:
    command: usr/bin/hibp-sort
    plugs: [files]
  topn:
    command: usr/bin/hibp-topn
    plugs: [files]
  convert:
    command: usr/bin/hibp-convert
    plugs: [files]

plugs:
  files:
    interface: home
  network:
    interface: network
  bind:
    interface: network-bind
    
parts:
  hibp:
    source: https://github.com/oschonrock/hibp.git
    plugin: cmake
    build-packages: [unzip, libcurl4-openssl-dev, libevent-dev, ruby, libtbb-dev]
    build-attributes:
      - enable-patchelf
    stage-packages: [libcurl4-openssl-dev, libevent-dev, libtbb-dev]
    override-build: |
      cd ../src
      git submodule update --init --recursive
      cd ext/restinio
      gem install Mxx_ru
      mxxruexternals
      cd ../..
      cd ../build
      snapcraftctl build
      
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=release
      - -DCMAKE_INSTALL_PREFIX=/usr
