name: hibp
base: core24
version: '0.1' 
summary: Have I been pawned database downloader, server and utilities
description: |
  High performance downloader, query tool, server and utilities for the
  Have I been Pawned database of compromiseed passwords. This very useful
  database is somewhat challenging to use locally because of its sheer size.
  These utiliities make it easy and fast to deal with the large data volume
  while being very effiicent on disk and memory resouces.

grade: stable
confinement: classic

lint:
  ignore:
    - library

apps:
  download:
    command: usr/bin/hibp-download
  search:
    command: usr/bin/hibp-search
  server:
    command: usr/bin/hibp-server
  join:
    command: usr/bin/hibp-join
  sort:
    command: usr/bin/hibp-sort
  topn:
    command: usr/bin/hibp-topn
  convert:
    command: usr/bin/hibp-convert
    
parts:
  hibp:
    source: https://github.com/oschonrock/hibp.git
    plugin: cmake
    build-packages: [unzip, libcurl4-openssl-dev, libevent-dev, ruby, libtbb-dev]
    build-attributes:
      - enable-patchelf
    stage-packages: [libcurl4-openssl-dev, libevent-dev, libtbb-dev]
    override-build: |
      cd ../src
      git submodule update --init --recursive
      cd ext/restinio
      gem install Mxx_ru
      mxxruexternals
      cd ../..
      cd ../build
      snapcraftctl build
      
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=release
      - -DCMAKE_INSTALL_PREFIX=/usr
