name: Debian 10: gcc-10

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Debian container
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace debian:latest /bin/bash -c "
          uname -a && 
          apt-get update &&
          apt-get install -y build-essential &&
          # Add your build commands here
          make && make test
          "
