name: Debian 11 gcc-10.2

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Debian container
        run: |
          docker run --rm -v $(pwd):/workspace -w /workspace debian:11-slim /bin/bash -c "
          apt-get update &&
          apt install -y build-essential \
            cmake \
            ninja-build \
            git \
            libcurl4-openssl-dev \
            libevent-dev \
            ruby \
            libtbb-dev &&
          cd ext/restinio &&
          gem install Mxx_ru &&
          mxxruexternals &&
          cd ../.. &&
          cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=debug -DNOPCH=ON -DBINFUSE_TEST=OFF -DHIBP_TEST=ON &&
          cmake --build build
          "
